### PR TITLE
View: Add Brand Brothers logo.

### PR DESCRIPTION
**Pull request by vonglasow**

### CODE REVIEW

**Comment by Hywan** [comment]
@vonglasow Where is the SVG file?

**Comment by vonglasow** [comment]
@Hywan https://www.brandbrothers.fr/img/bbros_w.svg

**Comment by Hywan** [comment]
@vonglasow https://static.hoa-project.net/Image/Logo/BrandBrothers.svg

**Comment by vonglasow** [comment]
@Hywan it's ok for the size you can review and merge ;)

**Comment by Hywan** [comment]
Thanks! Deployed.

**Pull request merged**
