### PR TITLE
Remove the archives related section, fix #87

### LINKED ISSUE #87: download.hoa-project.net is not up to date
Hi,

In the [documentation](http://hoa-project.net/En/Source.html), we propose http://download.hoa-project.net/ as a mirror to download archives of our libs. But all this archives are old. We need to choose between in one hand keep this possibility and maintain this mirror or down it in another hand.

It's not the only thing we have to keep in mind, for exemple the [API doc](http://api.hoa-project.net/) is not up to date too.

Maybe it's possible to automate the whole process with a hook on the github tag event ?

### PR DESCRIPTION
**Pull request by Jir4**
We are removing this sections please see #87.

### CODE REVIEW

**Comment by Hywan** [comment]
@osaris Please, review this PR. I will do the merge after your :+1:.

**Comment by osaris** [comment]
Perfect ! Thanks @Jir4  !

**Comment by Hywan** [comment]
Thanks! `master` and `preview` are updated. The website is updated too. nginx has been updated too. download.hoa-project.net returns a 404 now.

:clap:

**Comment by Jir4** [comment]
:+1: and what about `dav.hoa-project.net` ?

**Comment by Hywan** [comment]
It hosts our calendars, contacts, task lists etc. now. No longer the archives.

**Comment by Jir4** [comment]
ok

**Pull request merged**
