### PR TITLE
Draft the Hoa Apex 3rd edition page

### PR DESCRIPTION
**Pull request by Hywan**
* [x] Location,
* [x] Map,
* [x] Dates,
* [x] Transport,
* [x] Hotels,
  * [x] VLR,
* [x] Lunches,
* [x] Calendar
  * [x] Dedicated calendar,
  * [x] Correct view (waiting on a PR from @armin-hackmann),
* [x] Contacts.

### CODE REVIEW

**Comment by Hywan** [comment]
@vonglasow Plese, could you help me. I need:
* Subway connections to the location,
* Train connections,
* Bus connections,
* Foot “paths”.
What to do with lunches too?

@hoaproject/hoackers: What to do with hotels? Do we list some of them? I put a link to VLR but we can also put a link to Booking (cc @stephpy and @shouze)?

**Comment by Hywan** [comment]
Current page look:
screen shot 2015-08-03 at 08 33 59

**Comment by osaris** [comment]
For the hotels, many of us have already booked something but If you want to add some links, you can also add airbnb ;-)

The page looks good but the calendar is so big for so few informations ? Do you plan to do a day view on the two days with detailed plans ?

**Comment by Hywan** [comment]
@osaris See my ping to @armin-hackmann :smiley:. The PR I am waiting on will allow to set the view (day, week etc.) and stick on a specific date with specific settings (Monday is the 1st day of the week) etc. Will come soon (1 week) as he told me by email.

**Comment by Hywan** [comment]
@osaris The goal of having this calendar is people ability to subscribe to it.

**Comment by vonglasow** [comment]
__Subway connections to the location,__
So we have a lot of possibilities the most closer is ligne 8 or 9 stop at "Bonne Nouvelle"
You can use also ligne 7 stop at "Poissonière" and walk through the street.

__Train connections,__
If you stop at 
- "Gare du Nord" take the ligne 4 change at "Gare de l'est" and take ligne 7 (see above)
- "Gare de l'est" take the ligne 7 (see above)
- "Gare Montparnasse" take ligne 4 and change at Strasbourg Saint Denis and take ligne 8 or 9.
- "Gare de Lyon" take ligne 1 change at Reuilly Diderot and take ligne 8

__Bus connections,__
Ligne 20, 39, 48 stop at "Poissonnière bonne nouvelle"

__Foot “paths”. What to do with lunches too?__
A lot of possibility too lunch in the street.

**Comment by Hywan** [comment]
Waiting on the PR of @armin-hackmann to finish this one :-).

**Comment by armin-hackmann** [comment]
Hey, just so you have a better time table: The PR in question will come tomorrow evening (Europe/Berlin time) and hopefully on production not long after that :)

**Comment by Hywan** [comment]
@armin-hackmann Peeeerfect \o/. You rock man :dancer:.

**Comment by Hywan** [comment]
Modulo one CSS issue while taking the screenshot, the page looks like this now:
screen shot 2015-08-10 at 13 37 03

Thoughts?

**Comment by Grummfy** [comment]
For the transport information, it can be usefull to indicate the type of ticket (for people who are not living in Paris) to take.

**Comment by vonglasow** [comment]
:+1:

**Comment by vonglasow** [comment]
http://www.ratp.fr/en/ratp/r_61656/t-ticket/

**Comment by Hywan** [comment]
@Grummfy, @vonglasow Links to the RATP website is provided in the page, so it's fine enough :-).

**Pull request merged**
