### PR TITLE
Documentation: Fallback to `README.md` when hack book chapter is missing

### PR DESCRIPTION
**Pull request by Hywan**
Address https://github.com/hoaproject/ActionBoard/issues/17.

Library list on the homepage, before:
screen shot 2016-04-06 at 00 51 03

Library list on the homepage, after:
screen shot 2016-04-06 at 00 51 15

A hack book chapter showing the `README.md` extract:
screen shot 2016-04-06 at 00 51 43

The only relevant commit is this one: https://github.com/hoaproject/W3/commit/f4bef7f17db0d5af599e32596771ca67bc1380fb.

Please @hoaproject/hoackers, give me your feedbacks :-).

### CODE REVIEW

**Comment by harikt** [comment]
I agree, it may be good to give the users some information about the same. I have tried to use various components and due to lack of documentation I couldn't use the same. So if a component is ready it will be good to push with documentation.

Thank you for your energy and good work. The commits looks nice :) .

**Comment by harikt** [comment]
Also how about fix the readme that links to documentation page when there is none ? 

Eg : https://github.com/hoaproject/Acl it links back to the website .

**Comment by Grummfy** [comment]
good indeed.

thanks for the works!

+1 for the doc (already say) : it should point on the good section http://hoa-project.net/Literature/Hack/Acl.html instead of the whole website

**Comment by shulard** [comment]
Looks good for me too :+1: 

Love the idea to have a more consistent documentation (the READMEs are written to document library features and usage so use them is taking advantage of all the work done).

Thanks for your awesome work !

**Comment by Hywan** [comment]
About your requests to have a direct link to the hack book page in the Documentation Section of the `README.md` file, this is exactly what is going to be addressed by the https://github.com/hoaproject/ActionBoard/issues/17. This PR is 50% of the job.

**Comment by Hywan** [comment]
Deployed on `www`.

**Comment by Grummfy** [comment]
thanks

**Pull request merged**
